// Generated by hand from shared/protocol.md. That document is the source of truth.

export type BBox = {
  x: number;
  y: number;
  width: number;
  height: number;
};

export type JoinMessage = {
  type: "join";
  request_id: string;
  room_id: string;
  client_id: string;
};

export type PingMessage = {
  type: "ping";
  request_id: string;
  room_id: string;
};

export type ExplainRequestMessage = {
  type: "explain_request";
  request_id: string;
  room_id: string;
  bbox: BBox;
  annotated_frame_jpeg_base64: string;
  crop_jpeg_base64: string;
  thumbnail_jpeg_base64: string;
  audio_pcm16_base64: string;
  audio_sample_rate_hz: 16000;
  question: string;
  language: string;
};

export type FollowUpMessage = {
  type: "follow_up";
  request_id: string;
  room_id: string;
  parent_request_id: string;
  question: string;
  language: string;
};

export type ClientMessage =
  | JoinMessage
  | PingMessage
  | ExplainRequestMessage
  | FollowUpMessage;

export type AckMessage = {
  type: "ack";
  request_id: string;
  room_id: string;
  kind: "joined" | "pong" | "request_received";
  server_time: string;
};

export type TextDeltaMessage = {
  type: "text_delta";
  request_id: string;
  seq: number;
  delta: string;
};

export type GroundingMessage = {
  type: "grounding";
  request_id: string;
  grounding_quote: string;
  grounding_offset_seconds: number | null;
  confidence: number;
  region_label: string;
};

export type AudioDeltaMessage = {
  type: "audio_delta";
  request_id: string;
  seq: number;
  audio_pcm16_base64: string;
  audio_sample_rate_hz: number;
};

export type DoneMessage = {
  type: "done";
  request_id: string;
  latency_ms: number;
  audio_available: boolean;
};

export type ErrorMessage = {
  type: "error";
  request_id: string;
  code: string;
  message: string;
  retryable: boolean;
};

export type ServerMessage =
  | AckMessage
  | TextDeltaMessage
  | GroundingMessage
  | AudioDeltaMessage
  | DoneMessage
  | ErrorMessage;
